import { supabase } from "@/lib/supabase";
import { starterCalls, starterProperties } from "@/lib/mock-data";
import { CallRequest, Property, PropertyFormValues, formToPropertyInput } from "@/types";

const propertyKey = "sampadha-properties";
const callKey = "sampadha-call-requests";
const read = <T,>(key: string, fallback: T): T => { if (typeof window === "undefined") return fallback; const saved = window.localStorage.getItem(key); return saved ? JSON.parse(saved) as T : fallback; };
const write = (key: string, value: unknown) => window.localStorage.setItem(key, JSON.stringify(value));
export async function listProperties(): Promise<Property[]> { if (supabase) { const { data, error } = await supabase.from("properties").select("*").order("created_at", { ascending: false }); if (error) throw error; return data as Property[]; } return read(propertyKey, starterProperties); }
export async function listCalls(): Promise<CallRequest[]> { if (supabase) { const { data, error } = await supabase.from("call_requests").select("*").order("created_at", { ascending: false }); if (error) throw error; return data as CallRequest[]; } return read(callKey, starterCalls); }
export async function createProperty(): Promise<Property> { if (supabase) { const { data, error } = await supabase.rpc("create_property"); if (error) throw error; return data as Property; } const properties = read(propertyKey, starterProperties); const next = Math.max(0, ...properties.map((item) => Number(item.property_code.replace("SP", "")))) + 1; const now = new Date().toISOString(); const property: Property = { id: crypto.randomUUID(), property_code: `SP${String(next).padStart(3, "0")}`, name: "", keyword: "", location: "", google_maps_url: "", owner_name: "", contact_number: "", property_type: "", facing: "", dimension: "", total_area: null, area_unit: "sqft", price: null, price_unit: "sqft", total_price: null, visited: false, documents_collected: false, sold: false, created_at: now, updated_at: now, image_path: null, image_url: null }; write(propertyKey, [property, ...properties]); return property; }
export async function updateProperty(property: Property, form: PropertyFormValues): Promise<Property> { const input = formToPropertyInput(form); const updated = { ...property, ...input, updated_at: new Date().toISOString() } as Property; if (supabase) { const { data, error } = await supabase.from("properties").update(input).eq("id", property.id).select().single(); if (error) throw error; return data as Property; } write(propertyKey, read<Property[]>(propertyKey, starterProperties).map((item) => item.id === property.id ? updated : item)); return updated; }
export async function updatePropertyStatus(property: Property, patch: Partial<Pick<Property, "visited" | "documents_collected" | "sold">>): Promise<Property> { if (supabase) { const { data, error } = await supabase.from("properties").update(patch).eq("id", property.id).select().single(); if (error) throw error; return data as Property; } const updated = { ...property, ...patch, updated_at: new Date().toISOString() }; write(propertyKey, read<Property[]>(propertyKey, starterProperties).map((item) => item.id === property.id ? updated : item)); return updated; }
export async function createCall(input: Omit<CallRequest, "id" | "request_code" | "created_at" | "updated_at">): Promise<CallRequest> { if (supabase) { const { data, error } = await supabase.rpc("create_call_request", { payload: input }); if (error) throw error; return data as CallRequest; } const calls = read(callKey, starterCalls); const next = Math.max(0, ...calls.map((item) => Number(item.request_code.replace("RQ", "")))) + 1; const now = new Date().toISOString(); const request = { ...input, id: crypto.randomUUID(), request_code: `RQ${String(next).padStart(3, "0")}`, created_at: now, updated_at: now }; write(callKey, [request, ...calls]); return request; }
export async function updateCall(call: CallRequest, patch: Partial<CallRequest>): Promise<CallRequest> { const updated = { ...call, ...patch, updated_at: new Date().toISOString() }; if (supabase) { const { data, error } = await supabase.from("call_requests").update(patch).eq("id", call.id).select().single(); if (error) throw error; return data as CallRequest; } write(callKey, read<CallRequest[]>(callKey, starterCalls).map((item) => item.id === call.id ? updated : item)); return updated; }
