import { CallRequest, Property } from "@/types";

const now = "2026-09-20T08:00:00.000Z";
export const starterProperties: Property[] = [{
  id: "demo-1",
  property_code: "SP040",
  name: "Corner commercial site",
  keyword: "corner",
  location: "Hassan",
  google_maps_url: "",
  owner_name: "Ramesh",
  contact_number: "9876543210",
  second_contact_number: "",
  property_category: "sale",
  property_type: "Commercial Building",
  rental_type: "",
  rental_category: "",
  facing: "East",
  dimension: "30 x 40",
  floor: "",
  property_kind: "",
  total_area: 1200,
  area_unit: "sqft",
  price: 3500,
  price_unit: "sqft",
  total_price: 4200000,
  custom_price_enabled: false,
  custom_selling_price: null,
  rent_price: null,
  advance_price: null,
  visited: false,
  documents_collected: false,
  video_uploaded: false,
  sold: false,
  years_old: null,
  details: "",
  final_price: null,
  created_at: now,
  updated_at: now,
  image_path: null,
  image_url: null,
}];
export const starterCalls: CallRequest[] = [];